### ISSUE TITLE
Cant not rename the band for exporting to drive

### ISSUE THREAD

**Issue by seeyouinsight** [shilosh/ContinuousLST#1]
hi, I tried to run your code to produce the LSTcount , but It can not rename the band , can you give a solution for get it

**Comment by Rossymamat** [comment]
very good work. How can I  use it to larger area ?

**Comment by shilosh** [comment]
Can you be more specific? 
Which code exactly are you using? What is the error message?

**Comment by shilosh** [comment]
@Rossymamat, You can try and run the codes with a larger polygon, but I'm not sure GEE's assets can hold such an amount of data. Using Google Cloud may solve it, but I didn't try it myself.

**Comment by Rossymamat** [comment]
thanks for your quick response, I will try

shilosh ***@***.***> 于2021年11月9日周二 下午3:21写道：
